thich_nhat_hanh:
  - "thich nhat hanh"
  - "thích nhất hạnh"
  - "tnh"

marcus_aurelius:
  - "marcus aurelius"
  - "emperor marcus aurelius"

lao_tzu:
  - "lao tzu"
  - "laozi"
  - "lao zi"
  - "lao-tzu"

zen_proverb:
  - "zen proverb"
  - "zen saying"
  - "source uncertain"

seneca:
  - "seneca"
  - "lucius annaeus seneca"

bodhidharma:
  - "bodhidharma"
  - "daruma"

dogen:
  - "dogen"
  - "dōgen"
  - "dogen zenji"

tao_te_ching:
  - "tao te ching"
  - "dao de jing"
  - "dao-te ching"

shunryu_suzuki:
  - "shunryu suzuki"
  - "suzuki roshi"
  - "shunryu suzuki roshi"

epictetus:
  - "epictetus"
