Zen:
  - ["#BreathOfNow","#DailyPractice","#Zen","#Mindfulness","#Stillness","#Presence","#Meditation","#LettingGo","#Simplicity","#InnerPeace","#Journaling"]
  - ["#BreathOfNow","#ZenWisdom","#Calm","#SlowLiving","#Awareness","#Breathe","#Gratitude","#LiveLightly","#QuietMind","#Now"]
Tao:
  - ["#BreathOfNow","#Tao","#WuWei","#Flow","#Nature","#MindfulLiving","#Ease","#NonStriving","#SoftPower","#Presence","#Journaling"]
Stoic:
  - ["#BreathOfNow","#Stoic","#Stoicism","#MarcusAurelius","#Seneca","#Discipline","#Virtue","#Resilience","#SelfMastery","#DailyPractice","#Journaling"]
