Zen:
  keywords: ["woodcut", "linocut", "engraved", "organic", "serene"]
  square_footer: "ZEN • @breathofnow"
Tao:
  keywords: ["brush painting", "ink flow", "fluid", "nature", "dynamic"]
  square_footer: "TAO • @breathofnow"
Stoic:
  keywords: ["marble relief", "roman coin", "engraving", "structured", "civic", "enduring"]
  square_footer: "STOIC • @breathofnow"
